# Generated by Django 5.1.15 on 2026-04-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=20)),
                ('boss_name', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('NORMAL', 'Normal'), ('SAVAGE', 'Savage'), ('EXTREME', 'Extreme'), ('ULTIMATE', 'Ultimate')], max_length=20)),
                ('arena_shape', models.CharField(choices=[('SQUARE', 'Square'), ('CIRCLE', 'Circle')], default='CIRCLE', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RaidTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('expansion', models.CharField(blank=True, max_length=40)),
                ('patch', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
                ('phase_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('difficulty_rating', models.PositiveSmallIntegerField(default=1)),
                ('tags', models.JSONField(default=list)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='raids.fight')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('fight', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MechanicStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('narration', models.TextField(blank=True)),
                ('timer_seconds', models.PositiveSmallIntegerField(default=0)),
                ('action_type', models.CharField(choices=[('POSITION', 'Click a position on the arena'), ('CHOICE', 'Pick from a list of options')], default='POSITION', max_length=20)),
                ('arena_state', models.JSONField(default=dict)),
                ('choices', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='raids.mechanic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mechanic', 'order')},
            },
        ),
        migrations.AddField(
            model_name='fight',
            name='raid_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='raids.raidtier'),
        ),
        migrations.CreateModel(
            name='DrillResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TANK', 'Tank'), ('HEALER', 'Healer'), ('MELEE', 'Melee DPS'), ('RANGED', 'Ranged DPS'), ('CASTER', 'Caster DPS')], max_length=20)),
                ('submitted_x', models.FloatField(blank=True, null=True)),
                ('submitted_y', models.FloatField(blank=True, null=True)),
                ('submitted_choice', models.CharField(blank=True, max_length=80)),
                ('is_correct', models.BooleanField()),
                ('time_taken_ms', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raids.mechanicstep')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='raids.usersession')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TANK', 'Tank'), ('HEALER', 'Healer'), ('MELEE', 'Melee DPS'), ('RANGED', 'Ranged DPS'), ('CASTER', 'Caster DPS')], max_length=20)),
                ('correct_position', models.JSONField(default=dict)),
                ('tolerance', models.FloatField(blank=True, null=True)),
                ('alt_positions', models.JSONField(default=list)),
                ('correct_choice', models.CharField(blank=True, max_length=80)),
                ('safe_zones', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_variants', to='raids.mechanicstep')),
            ],
            options={
                'unique_together': {('step', 'role')},
            },
        ),
    ]
