# Generated by Django 5.1.15 on 2026-04-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicstep',
            name='default_tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
