# Generated by Django 5.1.15 on 2026-04-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0002_mechanicstep_default_tolerance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolevariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='drillresult',
            name='spot',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AddField(
            model_name='fight',
            name='arena_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='boss_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='rolevariant',
            name='spot',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AlterField(
            model_name='drillresult',
            name='role',
            field=models.CharField(choices=[('TANK', 'Tank'), ('HEALER', 'Healer'), ('MELEE', 'Melee DPS'), ('RANGED', 'Ranged DPS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolevariant',
            name='role',
            field=models.CharField(choices=[('TANK', 'Tank'), ('HEALER', 'Healer'), ('MELEE', 'Melee DPS'), ('RANGED', 'Ranged DPS')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='rolevariant',
            unique_together={('step', 'role', 'spot')},
        ),
    ]
